name: CI (macOS)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python: [3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Install macOS-specific deps
        run: |
          pip install "plyer[macosx]"

      - name: Run Tests
        run: pytest -q
